### ISSUE TITLE
Results don't match paper

### ISSUE THREAD

**Issue by mees** [xcyan/nips16_PTN#2]
Hi,
I downloaded the pretrained models and after running run ./eval_models.sh and got these numbers
CNN-VOL IOU = 0.500177	PTN-COMB IOU = 0.509016	PTN-PROJ IOU = 0.503761	
they are not far off, but still don't correspond to the paper numbers, any idea why I am getting different results?

**Comment by xcyan** [comment]
Please note that the pretrained model was based on the cleaned up version of our code. It is not possible to replicate the exact same results because the training batches are sampled randomly.
