### ISSUE TITLE
Can't test the trained encoder

### ISSUE THREAD

**Issue by mees** [xcyan/nips16_PTN#3]
Hi,
I trained the single class encoder with ./demo_pretrain_singleclass.sh. Now I wanted to evaluate the trained models. So in eval_quant_test.lua I just changed the name of the loaded file (cnn_vol.t7) to the last trained model:
base_loader = torch.load(opt.checkpoint_dir .. 'arch_rotatorRNN_singleclass_nv24_adam2_bs8_nz512_wd0.001_lbg10_ks16/net-epoch-20.t7')
encoder = base_loader.encoder
base_voxel_dec = base_loader.voxel_dec

When I run the testcript eval_models.sh I get following error:
/home/meeso/torch/install/bin/luajit: scripts/eval_quant_test.lua:90: attempt to index global 'base_voxel_dec' (a nil value)
stack traceback:
	scripts/eval_quant_test.lua:90: in main chunk
	[C]: in function 'dofile'
	...eeso/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

Any idea how I fix this?

**Comment by xcyan** [comment]
You need to train a voxel decoder for test.

**Comment by mees** [comment]
Ah okey you are right. But it seems that in the code the encoder doesn't get loaded:
https://github.com/xcyan/nips16_PTN/blob/789031e2c6d63648a1debc2134dd7fd525bf735f/scripts/train_PTN.lua#L108
Not sure if its the commented out lines later, but I think a torch.load() is missing somewhere in the code right? Or how can I tell him to use my trained encoder for the training?

Also, is there some method for storing a log with the train and test loss? At least this way one could see if the trained encoder is performing, or how do you monitor it?

**Comment by xcyan** [comment]
You are right. This should be fixed.

Add back the two lines:
loader = torch.load(opt.checkpoint_dir .. opt.basemodel_name ..
string.format('/net-epoch-%d.t7', opt.basemodel_epoch))
encoder = loader.encoder

**Comment by mees** [comment]
Thanks, I also had to change the name  'rotatorRNN1_64' to 'arch_rotatorRNN'

**Comment by xcyan** [comment]
Fixed the bug reported by @mees 
https://github.com/xcyan/nips16_PTN/commit/8cf26ed6d217c50a7503c499a225246a7f3419a2
