### ISSUE TITLE
Only half of the training data is used

### ISSUE THREAD

**Issue by mees** [xcyan/nips16_PTN#5]
In https://github.com/xcyan/nips16_PTN/blob/master/scripts/train_rotatorRNN_base.lua#L274  in the expression math.min(data:size() * opt.nview / 2 , opt.ntrain), I don't understand where the division by two is coming. data:size() is the number of trainings scenes you have, 4744 in this case, and you have 24 views per scene, so multiplication makes sense, but why divide it by two. Maybe I missed something, but it seems that only half of the views/data is used?

**Comment by xcyan** [comment]
We found that training with such epochs is sufficient. You can train more iterations for your purpose.
