### ISSUE TITLE
Data corrupted

### ISSUE THREAD

**Issue by HaiyongJiang** [xcyan/nips16_PTN#6]
Hi Doc. @xcyan, I encountered the following problem during running "eval_models.sh". 
`torch/install/share/lua/5.1/torch/File.lua:351: read error: read 39866875 blocks instead of 46656000 at torch/pkg/torch/lib/TH/THDiskFile.c:356`
I thought it is because of the data corruption. Could you please share the checksum of the pretrained models for the data validation? Thank you.

**Comment by xcyan** [comment]
@HaiyongJiang Which model you downloaded is not working?

**Comment by HaiyongJiang** [comment]
cnn_vol.t7, ptn_proj.t7 and ptn_comb.t7 are corrupted. I think it is mainly because the downloading process was interrupted. So it would be better if you can share the checksum of these models for the data validation. Thank you.

**Comment by xcyan** [comment]
I did simple checksum with the results below:
`$ cksum cnn_vol.t7`
`$ 1482309979 1654479999 cnn_vol.t7`
`$ cksum ptn_proj.t7`
`$ 2239664078 1654479810 ptn_proj.t7`
`$ cksum ptn_comb.t7`
`$ 3450348569 1654479999 ptn_comb.t7`

**Comment by HaiyongJiang** [comment]
Thank you.
