### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Santubasa** [xcyan/nips16_PTN#7]
Hi,
I was just evaluating the pretrained model and encountered the following issue regarding the memory space of the gpu,
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1355/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/sbasavaraju/torch/install/bin/luajit: ...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-1355/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'read'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:351: in function <...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sbasavaraju/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sbasavaraju/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...e/sbasavaraju/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	scripts/eval_quant_test.lua:63: in main chunk
	[C]: in function 'dofile'
	...raju/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

I have Ubuntu 14,04 with graphics model NVIDIA GeForce GTX 470 1 GB , is the graphics not sufficient to run the program ?

Thanks

**Comment by xcyan** [comment]
No you need to have at least 8G card. You can try to run the code with
smaller batchsize and learning rate. But I cannot guarantee the performance.
